#!/usr/bin/env node
/* Compile shared academic JSON to readable static HTML. No runtime dependency. */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(root, 'assets/data/gmn-2026-2027.json'), 'utf8'));
const check = process.argv.includes('--check');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = value => new Date(`${value}T12:00:00Z`).toLocaleDateString('es-ES', {day:'numeric', month:'long', year:'numeric', timeZone:'UTC'});
const teacher = m => m.teacher || 'Profesor actualmente no indicado';
const countEvidence = m => data.evidence.filter(e => e.moduleCodes.includes(m.code)).length;
const link = ([text,href]) => `<a href="${esc(href)}">${esc(text)}</a>`;
const writes = [];
function write(file, content) {
  const target = path.join(root, file);
  const previous = fs.existsSync(target) ? fs.readFileSync(target,'utf8') : '';
  if (previous === content) return;
  if (check) { writes.push(file); return; }
  fs.mkdirSync(path.dirname(target), {recursive:true});
  fs.writeFileSync(target,content);
  writes.push(file);
}
function replaceBlock(file, name, content) {
  const s = fs.readFileSync(path.join(root,file),'utf8');
  const start = `<!-- gmn:${name}:start -->`, end = `<!-- gmn:${name}:end -->`;
  const a = s.indexOf(start), b = s.indexOf(end);
  if (a < 0 || b < a) throw new Error(`Missing ${name} markers in ${file}`);
  write(file, s.slice(0,a+start.length)+'\n'+content+'\n'+s.slice(b));
}
const layers = `<div class="n3-grid">
<article class="n3-layer"><span class="n3-badge">● Presente · real / actual</span><h3>Lo que existe hoy</h3><p>Diego David, la formación GMN, la historia de primero y el inicio confirmado de segundo. Aprendizajes y evidencias se incorporan cuando se documentan.</p><a href="formacion-gmn.html">Conocer la formación →</a></article>
<article class="n3-layer"><span class="n3-badge n3-badge--prototype">◐ Prototipo · académico</span><h3>Lo que estamos diseñando</h3><p>Catálogo, Escuela, reservas simuladas, packs, gestión, material y Logbook. Sistemas de demostración sin servicios comerciales operativos.</p><a href="proyecto-intermodular.html#matriz">Ver cómo se conecta →</a></article>
<article class="n3-layer"><span class="n3-badge n3-badge--future">○ Futuro · visión / estudio</span><h3>Lo que podría llegar</h3><p>Base, Campamento, Hangar, flota, viajes e infraestructura. Ideas sujetas a investigación, recursos y validación, sin aperturas anunciadas.</p><a href="horizonte-nomada.html">Explorar el horizonte →</a></article></div>`;
const summary = `<div class="n3" lang="es" translate="no"><span class="n3-badge">Presente · ${esc(data.year)} en curso</span><h2>${esc(data.year)} · ${esc(data.course)}</h2><p>${esc(data.stage)} en el ${esc(data.center)} de ${esc(data.locality)}. Inicio: <time datetime="${data.startDate}">${date(data.startDate)}</time>.</p><p>${data.modules.length - 1} módulos + Fase de Empresa II. Las diez áreas académicas están contempladas; conexiones con el proyecto en desarrollo.</p><div class="n3-actions"><a class="n3-button" href="segundo-gmn.html">Conocer el curso</a><a class="n3-button n3-button--quiet" href="proyecto-intermodular.html">Proyecto Intermodular →</a></div></div>`;
const dashboard = `<dl class="n3-stats"><div><dt>Curso activo</dt><dd>${esc(data.year)}<small>${esc(data.course)}</small></dd></div><div><dt>Áreas contempladas</dt><dd>${data.modules.length} / ${data.modules.length}<small>9 módulos + Fase de Empresa II</small></dd></div><div><dt>Estado del proyecto</dt><dd>${esc(data.status)}<small>Proyecto no operativo</small></dd></div></dl><div class="im-meta"><span>${esc(data.center)} · ${esc(data.locality)}</span><span>Inicio: ${date(data.startDate)}</span><span>Actualización: <time datetime="${data.updatedAt}">${date(data.updatedAt)}</time></span></div>`;
const matrix = `<div id="module-matrix">${data.modules.map(m=>`<article class="im-matrix-item" data-module-area="${esc(m.area)}" data-module-search="${esc([m.code,m.name,m.teacher,m.area,m.knowledge,m.application].join(' '))}"><span class="im-code">${m.code}</span><div><h3><a href="#${m.chapter}">${esc(m.name)}</a></h3><p>${esc(teacher(m))}${m.optional?' · Optativa':''}</p><p>${esc(m.area)} · ${esc(m.knowledge)}</p></div><div class="im-matrix-state"><span class="n3-badge n3-badge--prototype">${esc(m.status)}</span><small><time datetime="${m.updatedAt}">${m.updatedAt}</time></small></div></article>`).join('\n')}</div>`;
const modules = data.modules.map(m=>`<article class="im-module" id="${m.chapter}"><div class="im-module-head"><div><span class="n3-kicker">${m.code} · ${esc(m.area)}${m.optional?' · Optativa':''}</span><h3>${esc(m.name)}</h3><p>${esc(teacher(m))}</p></div><span class="n3-badge n3-badge--prototype">${esc(m.status)}</span></div><dl class="im-flow">${[['Conocimiento',m.knowledge],['Decisión',m.decision],['Aplicación',m.application],['Resultado',m.result]].map(([a,b])=>`<div><dt>${a}</dt><dd>${esc(b)}</dd></div>`).join('')}</dl><div class="n3-actions">${m.links.map(link).join(' · ')}</div></article>`).join('\n');
const moduleList = `<div class="n3-table-wrap" tabindex="0" role="region" aria-label="Matrícula de segundo"><table class="n3-table"><caption>Matrícula facilitada por el autor · ${esc(data.course)} · 9 módulos + Fase de Empresa II</caption><thead><tr><th scope="col">Código</th><th scope="col">Asignatura</th><th scope="col">Profesorado</th></tr></thead><tbody>${data.modules.map(m=>`<tr><td>${m.code}</td><th scope="row"><a href="proyecto-intermodular.html#${m.chapter}">${esc(m.name)}</a>${m.optional?' <small>· Optativa</small>':''}</th><td>${esc(teacher(m))}</td></tr>`).join('')}</tbody></table></div>`;
const journal = "";
const roadmap = `<div class="im-timeline">${data.milestones.map(m=>`<article><small>${esc(m.period)} · ${esc(m.status)}</small><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p></article>`).join('')}</div>`;
const evidence = "";
const indicators = `<div class="n3-table-wrap" tabindex="0" role="region" aria-label="Indicadores ambientales propuestos"><table class="n3-table"><caption>Propuesta de indicadores · todos pendientes de línea base</caption><thead><tr><th scope="col">Indicador</th><th scope="col">Medida prevista</th><th scope="col">Fuente que se deberá aportar</th></tr></thead><tbody>${[['Residuos','kg por actividad / separación','Pesaje y registro de destino'],['Movilidad','km y ocupación del transporte','Registro de desplazamientos'],['Energía','kWh por periodo','Medición o documentación de consumo'],['Agua','Litros por actividad o periodo','Medición y alcance declarado'],['Capacidad de carga','Grupo y condiciones del espacio','Criterio técnico y permisos del entorno'],['Material reutilizable','Usos, mantenimiento y reparación','Historial del inventario'],['Emisiones estimadas','kg CO₂e con método explícito','Datos de actividad y factores documentados'],['Proveedores locales','Proporción con criterio geográfico','Registros de compras, cuando existan'],['Conservación e impacto','Observaciones e incidencias','Ficha de entorno'],['Educación ambiental','Objetivos y evaluación','Guion de sesión y reflexión'],['Cumplimiento','Criterios revisados / pendientes','Lista de requisitos y revisión']].map(r=>'<tr>'+r.map(c=>`<td>${esc(c)}</td>`).join('')+'</tr>').join('')}</tbody></table></div>`;
let template = fs.readFileSync(path.join(__dirname,'templates/intermodular.html'),'utf8');
const chapters = [...template.matchAll(/id="([^"]+)" data-chapter="([^"]+)"/g)].map(m=>[m[1],m[2]]);
const chapterOptions = chapters.map(([id,title],i)=>`<option value="${id}">${String(i+1).padStart(2,'0')} · ${title}</option>`).join('');
const chapterLinks = chapters.map(([id,title],i)=>`<a href="#${id}">${String(i+1).padStart(2,'0')} / ${title}</a>`).join('');
const vars={dashboard,layers,matrix,modules,evidence,journal,roadmap,indicators,chapterOptions,chapterLinks,areaOptions:[...new Set(data.modules.map(m=>m.area))].map(a=>`<option>${esc(a)}</option>`).join('')};
template = template.replace(/\{\{(\w+)\}\}/g,(_,key)=>{if(!(key in vars))throw new Error(key);return vars[key];});
function page(title, description, body, filename) {
 const url = `https://diegodavidextremo.github.io/nomada-extremo/${filename}`;
 return `<!DOCTYPE html>\n<html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="author" content="Diego David Extremo"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${url}"><meta property="og:image" content="https://diegodavidextremo.github.io/nomada-extremo/assets/images/noext/hero-principal.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="icon" href="assets/icons/favicon.ico"><link rel="manifest" href="site.webmanifest"><link rel="stylesheet" href="assets/css/styles.css"><link rel="stylesheet" href="assets/css/design-system.css?v=20260921-1"><link rel="stylesheet" href="assets/css/intermodular.css?v=20260914-3"></head>\n<body class="intermodular-page"><div id="nav-placeholder"></div><main id="main-content" class="n3" lang="es" translate="no">\n${body}\n</main><div id="footer-placeholder"></div><script src="assets/js/components.js?v=20260921-1"></script><script src="assets/js/main.js?v=20260921-1"></script><script src="assets/js/intermodular.js?v=20260914-3"></script><script src="assets/js/stage3.js?v=20260914-3"></script><script src="assets/js/chatbot.js?v=20260920-4"></script></body></html>\n`;
}
write('proyecto-intermodular.html',page('Proyecto Intermodular 2026-2027 · NÓMADA EXTREMO 3.0','Memoria central de 2.º GMN: diez áreas académicas, decisiones, bienestar animal, seguridad, sostenibilidad, viabilidad y planificación. Proyecto no operativo.',template,'proyecto-intermodular.html'));
const history = fs.readFileSync(path.join(__dirname,'templates/segundo-historico.html'),'utf8');
const second = `<section class="im-hero"><div class="n3-shell"><span class="n3-kicker">Etapa Intermodular · ${esc(data.center)} · ${esc(data.locality)}</span><span class="n3-badge">Presente · curso activo</span><h1>2.º GMN.<span>${esc(data.course)}</span></h1><p class="n3-lead">Aprender a guiar, proteger, organizar y documentar. Segundo curso del Grado Medio de Guía en el Medio Natural y de Tiempo Libre.</p>${dashboard}<div class="n3-actions"><a class="n3-button n3-button--light" href="proyecto-intermodular.html">Abrir la memoria intermodular</a></div></div></section><div class="n3-shell"><section class="n3-section" id="modulos-title"><span class="n3-kicker">Matrícula confirmada por el autor</span><h2>9 MÓDULOS +<br>FASE DE EMPRESA II.</h2><p>Los nombres, códigos y docentes se reproducen según la matrícula facilitada. El profesor de Fase de Empresa II no está indicado. El detalle académico se presenta en español.</p>${moduleList}</section><section class="n3-section" id="pilares-title"><h2>APRENDIZAJE QUE<br>CONSTRUYE CRITERIO.</h2><p>Seguridad, aventura, organización y sostenibilidad se conectan con decisiones del proyecto. Los módulos ecuestres se integran desde el bienestar animal. Las aplicaciones propuestas y evidencias se consultan en la memoria central.</p><div class="n3-actions"><a class="n3-button" href="proyecto-intermodular.html#matriz">Explorar matriz intermodular</a><a href="proyecto-intermodular.html#bienestar-animal">Política de bienestar animal</a></div></section><span id="bitacora" hidden></span><section class="n3-section"><h2>DE PRIMERO<br>A LA ETAPA INTERMODULAR.</h2>${roadmap}<details class="n3-history" data-history><summary>Archivo histórico · lo que esperaba de segundo antes del inicio</summary><p class="n3-note">Actualización · 14 septiembre 2026. Este contenido fue escrito al finalizar 1.º GMN. Desde el inicio de 2.º se conocen las materias y asignaciones docentes facilitadas arriba. Se conserva como testimonio de las expectativas de entonces.</p>${history}</details></section></div>`;
write('segundo-gmn.html',page('2.º GMN · Curso 2026-2027 | NÓMADA EXTREMO','Segundo curso activo desde el 14 de septiembre de 2026 en el IES Europa de Águilas: matrícula, docentes y Proyecto Intermodular.',second,'segundo-gmn.html'));
replaceBlock('index.html','home',`<section class="n3 n3-home-intro n3-section" lang="es" translate="no"><div class="n3-shell"><span class="n3-kicker">NÓMADA EXTREMO 3.0 · Curso ${esc(data.course)}</span>${summary}${layers}</div></section>`);
replaceBlock('formacion-gmn.html','summary',`<section class="n3-section n3-shell">${summary}${moduleList}</section>`);
if (check && writes.length) { console.error('Bloques académicos desactualizados:',writes.join(', ')); process.exitCode=1; }
else console.log(check?'Datos y HTML sincronizados.':`Generados ${writes.length} archivos académicos.`);
